version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: desafio_xp
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3333:3333
    environment:
      MYSQL_HOST: us-cdbr-east-06.cleardb.net
      MYSQL_USER: b0747f0db43837
      MYSQL_PASSWORD: 369b038a,
      JWT_SECRET: f39da548ea27c6bd2992a8e618c35b90
      MYSQL_DATABASE: heroku_770f16010c89f53
      HOSTNAME: db
  db:
    container_name: desafio_xp_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: desafio_xp_net